add multiple verify steps

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -67,6 +67,11 @@ jobs:
     - name: Check EKS Cluster Status
       run: aws eks describe-cluster --name minimal-eks-cluster --query "cluster.status"
 
+    - name: Debug kubeconfig Path
+      run: |
+        ls -lah $HOME/.kube
+        cat $HOME/.kube/config || echo "❌ kubeconfig file not found!"
+
     - name: Upload kubeconfig as an artifact
       uses: actions/upload-artifact@v4   #artifact v3 has deprecated
       with:
